words = {
        "easy": ["cat", "dog", "fish", "apple", "star", "moon", "cloud", "tree", "bird", "wind", 
                 "house", "cake", "sock", "ball", "car", "book", "pencil", "computer", "lamp", "dog", 
                 "river", "plane", "grass", "pen", "shoe", "tiger", "sun", "rain", "snow", "box", "city",
                 "hat", "juice", "bag", "orange", "ant", "chicken", "glove", "table", "phone", "chair", 
                 "desk", "toy", "ring", "rocket", "moonlight", "water", "shoes", "cloud", "basket", "sand",
                 "stone", "keyboard", "piano", "balloon", "candy", "ship", "starfish", "fence", "fishbowl",
                 "light", "cheese", "clock", "socks", "fire", "sunset", "earth", "mountain", "dream", 
                 "jungle", "toybox", "hatchet", "applejack", "umbrella", "mirror", "vacuum", "robot", "nut",
                 "glitter", "cookie", "bucket", "shadow", "guitar", "laptop", "volcano", "thunder", "harbor", 
                 "mist", "lava", "dinosaur", "magnet", "train", "telescope", "biscuit", "neutron", "cloudy",
                 "rocketship", "beach", "safari", "forest", "field", "mountain", "zebra", "parrot", "drum", 
                 "camp", "peach", "basketball", "lemon", "jacket", "trolley", "hammer", "flashlight", "toaster",
                 "wave", "sunflower", "cow", "trolley", "lighthouse", "ballpark", "guitar", "rainbow", "swing",
                 "grapes", "moonlight", "puzzle", "treasure", "music", "brush", "plankton", "dandelion", "hatchet"],
        "medium": ["python", "rocket", "planet", "jungle", "castle", "moonlight", "universe", "diamond", 
                   "guitar", "journey", "mountain", "coaster", "village", "pirate", "parrot", "island", "robot", 
                   "grape", "cherry", "pyramid", "silver", "glove", "telescope", "vulture", "explorer", "treasure", 
                   "galaxy", "lighthouse", "umbrella", "autumn", "library", "snowflake", "mermaid", "echo", 
                   "harbor", "school", "dinosaur", "crystal", "butterfly", "sailboat", "pirate", "toaster", "scooter",
                   "elephant", "avocado", "poison", "planetarium", "candle", "tropical", "hero", "treasure", 
                   "beach", "skylight", "biscuit", "unicorn", "clock", "hermit", "cheese", "vampire", "tiger",
                   "falcon", "astronomy", "satellite", "bat", "magma", "rocketship", "paradox", "pulse", 
                   "circuit", "seashell", "moonstone", "galaxy", "forest", "vortex", "echo", "volcano", "science", 
                   "hologram", "puzzle", "adventure", "meadow", "waves", "glacier", "fountain", "tornado", "whale",
                   "starfish", "carrot", "demon", "scorpion", "yellow", "orange", "indigo", "tangerine", "mango",
                   "skeleton", "adventure", "unicorn", "safari", "polar", "redwood", "tornado", "hawk", "penguin",
                   "crater", "astronaut", "constellation", "lightning", "treasure", "butterfly", "scientist", "rover"],
        "hard": ["elephant", "astronaut", "champion", "dinosaur", "adventure", "tornado", "supernova", "platinum", 
                 "architecture", "scorpion", "zodiac", "chocolate", "meridian", "vibration", "intelligence", 
                 "mandolin", "volcano", "volunteer", "dynamics", "fireworks", "paradox", "biography", "hurricane", 
                 "blackhole", "giraffe", "mystic", "chemistry", "parallel", "whirlwind", "cyclone", "electricity", 
                 "mutation", "machine", "hologram", "jetstream", "zeppelin", "laboratory", "photography", "alchemy", 
                 "meteor", "quicksilver", "planetarium", "mutation", "incognito", "galactic", "starship", "circuitry", 
                 "heartbeat", "quicksand", "waterfall", "revolution", "satellite", "illusion", "imagination", "alchemy",
                 "velocity", "geometry", "synergy", "pottery", "spacecraft", "photon", "aerospace", "monarchy", 
                 "volition", "fibonacci", "turbulence", "astrophysics", "spectrum", "orchestra", "bioluminescence", 
                 "biorhythm", "mercury", "frostbite", "parallax", "alchemy", "volition", "astral", "xenon", "exoplanet", 
                 "mathematics", "galaxy", "comet", "sunshine", "timewarp", "astronomy", "cyclone", "apocalypse", 
                 "amplifier", "fusion", "entropic", "subatomic", "constellation", "nanoparticle", "radiation", "neutron",
                 "supercomputer", "neural", "holography", "bioengineering", "astrobiology", "cybernetic", "quantum", 
                 "neuroscience", "matrix", "neutrinos", "darkmatter", "chaos", "thermodynamics", "stringtheory", "pulse", 
                 "entropy", "cellular", "cognition", "polymorph", "giga", "photon", "sensor", "energy", "dimensional", 
                 "neuromancer", "quanta", "particle", "quantum", "geocentric", "ultraviolet", "superconductivity", 
                 "gravitational", "seismic", "electromagnetic", "tachyon", "theory", "chronomancy", "hyperspace"],
        "impossible": ["sigma"]
    }
